CREATE TABLE IF NOT EXISTS towns(townID  INT NOT NULL PRIMARY KEY,name VARCHAR(255) NOT NULL, code VARCHAR(3) NOT NULL);
CREATE TABLE IF NOT EXISTS registrationNumbers(regNumber VARCHAR(30) NOT NULL, townID INT, FOREIGN KEY (townID) REFERENCES towns(townID));
